### ISSUE TITLE
how to upload local file from command line?

### ISSUE THREAD

**Issue by TangMonk** [shichao-an/115wangpan#20]

**Comment by shichao-an** [comment]
Hi,

Currently, uploading files from CLI has not been implemented. [115up](http://115wangpan.readthedocs.org/en/latest/cli.html#up) can only upload torrents for BT tasks. You can write code to upload files to your directories, see http://115wangpan.readthedocs.org/en/latest/tutorial.html#upload-files

**Comment by TangMonk** [comment]
I see, thanks
