### ISSUE TITLE
Failed to get download URL

### ISSUE THREAD

**Issue by raycraft** [shichao-an/115wangpan#23]
>>> f = files[0]
>>> f.url
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/u115/api.py", line 1240, in url
    return self.get_download_url()
  File "/usr/lib/python2.6/site-packages/u115/api.py", line 1234, in get_download_url
    self.api._req_files_download_url(self.pickcode, proapi)
  File "/usr/lib/python2.6/site-packages/u115/api.py", line 886, in _req_files_download_url
    raise RequestFailure('Failed to get download URL.')
u115.api.RequestFailure: Failed to get download URL.

**Comment by shichao-an** [comment]
Hi,

Can you provide additional information? The only one I see here is that you used Python 2.6.
What is the release for 115wangpan you used? Is your account VIP or non-VIP?

If you use the latest release or the master branch, can you enable debug logging (with the following code) and please copy and paste and output here? (you may want to mask your credentials such as username and passwords in the JSON output.)

```python
import logging
import u115
# somewhere in your code
logger = logging.getLogger('API')
logger.setLevel(logging.DEBUG)
# your code ...
f = files[0]
f.url
```

**Comment by shichao-an** [comment]
Hi @raycraft ,

I encounter the same problem as yours when getting the download url (`proapi=False`). I think it's due to 115.com's api policy change. I'll fix that soon.
