### ISSUE TITLE
After an "exceeding the max tasks amount" error, keeps receiving "Torrent upload failed. Please try again later."

### ISSUE THREAD

**Issue by riaqn** [shichao-an/115wangpan#25]
I 'm a VIP of 115. When I do `add_task_bt()` continuously and there 're too many tasks(say 20 concurrent tasks), then I receive an error saying "超出最大任务数量"(exceeding the max allowed tasks amount), which is the expected behaviour.

So I `sleep(30)` and try to `add_task_bt()` again, expecting to either successfully add the task, or receive another same error. However, I then keeps getting "Torrent upload failed, Please try again later" error, and even after several minutes some of the tasks in the queue is finished(so there 's space for a new task), I keeps seeing this error.

Restarting my program and re`login()`, and I can `add_task_bt()` smoothly.

**Comment by riaqn** [comment]
oops, didn't expect the title changing will reflect in the page.

**Comment by riaqn** [comment]
Sorry, my bad. The bug is on my side. I did some modify to the API of `add_task_bt()` so that it receive a file-like object instead of a filename. The problem is that when I re-issue an `add_task_bt()` the file-like object 's cursor is not reset to the head, and the uploaded torrent is empty, which lead to the error.
Sorry for the noise, closing the issue.

**Comment by shichao-an** [comment]
Glad to see you have solved the problem yourself!
