### ISSUE TITLE
多wan下只能单wan的速度

### ISSUE THREAD

**Issue by zeroleo12345** [shichao-an/115wangpan#28]
用115浏览器下载，在多wan环境下有叠加效果，是否因为支持多线程下载的关系，搞不懂，望指教。
python是否也可以支持？

**Comment by shichao-an** [comment]
你好，

目前这个 API 只支持单线程。下载功能（`API.download`）使用的是一个非常简单的库 [homura](https://github.com/shichao-an/homura)（基于 [PycURL](http://pycurl.sourceforge.net/)）。我不太了解115浏览器下载的具体实现（包括 VIP下载和极速下载的细节）。

关于多 WAN，我也不太知道代码如何受到多 WAN 环境的影响，毕竟手头没有这种环境可以测试。如果你有什么好的方案或实现，欢迎 pull request 或者讨论。

谢谢！

**Comment by zeroleo12345** [comment]
现在用的mwan3多播，我要先摸清楚负载均衡策略是按ip还是按会话。回家再研究下，用wget下载同一个地址，看看速度是否有叠加效果先，如果均衡策略是按ip，即使多线程下载估计也没有办法实现叠加效果。

**Comment by zeroleo12345** [comment]
已经验证过了，路由的负载均衡一般基于ip，可以按源ip或目标ip选择wan出口。验证步骤大约如下：
curl --interface eth1 -O http://intop.newhua.com:82/down/43.0.2357.132_chrome_installer.zip
curl --interface eth1:1 -O http://intop.newhua.com:82/down/43.0.2357.132_chrome_installer.zip
首先多次ping /intop.newhua.com，看返回ip是否不变，排除服务器有部署cdn分发到其他节点的影响，就是保证目标ip是固定的，然后eth1和eth1:1分配不同ip，路由按源ip选wan出口即可实现叠加效果。

方案：
在115网盘实现多wan叠加，就要看看服务器下载的时候能不能够分块下载，然后用多个线程或多进程下载，然后cat在一起，参数大概如下：curl -r 0-10240--interface eth1
python代码还是第一两次看，你那边能否帮忙验证一下115下载能否实现分块？支持分块，后面的才能实现。

**Comment by shichao-an** [comment]
@zeroleo12345 

115 下载链接支持 byte range，你可以导出一个下载链接用 curl 进行尝试。

你所描述的问题我觉得主要是下载部分。这个 API 下载功能是分离出来的，正如我前面评论提到的，使用的一个外部库 [homura](https://github.com/shichao-an/homura)，因此功能非常有限，只是为了提供一个最基本的下载功能。

这样做的初衷是提倡用户使用其他现成的工具来处理更高要求的下载任务。因为 115 并不在 session 上做限制，导出的链接可以使用 wget, aria2c, 迅雷等软件进行下载。

所以我认为是不是可以使用其他工具，或者其他支持多线程 HTTP 分块下载的库（不局限于 Python）来完成这件事情呢？毕竟这个已经超出了 API 本身的工作。
