### ISSUE TITLE
如何可以返回全部task

### ISSUE THREAD

**Issue by zeroleo12345** [shichao-an/115wangpan#29]
def _req_lixian_task_lists(self, page=1):
        """
        This request will cause the system to create a default downloads
        directory if it does not exist
        """
        url = 'http://115.com/lixian/'
        params = {'ct': 'lixian', 'ac': 'task_lists'}
        self._load_signatures()
        data = {
            'page': page,
            'uid': self.user_id,
            'sign': self._signatures['offline_space'],
            'time': self._lixian_timestamp,
        }
        req = Request(method='POST', url=url, params=params, data=data)
        res = self.http.send(req)

你好， 请教一下， 每次我调用这里的时候， res都只会返回4个任务， 但是我在浏览器登陆115是有很多任务的，没有返回全部？

**Comment by shichao-an** [comment]
你好，你是否尝试使用了 [API.get_tasks()](https://github.com/shichao-an/115wangpan/blob/master/u115/api.py#L411)？

比如：

```python
res = api.get_tasks(100)
```

**Comment by zeroleo12345** [comment]
使用了默认参数
tasks = api.get_tasks()

刚才试了100也不行

**Comment by shichao-an** [comment]
在代码开始处加上启用 debug：

```python
logger = logging.getLogger('API')
logger.setLevel(logging.DEBUG)
```

然后运行 `api.get_tasks()` 把输出的内容复制粘贴一下看看。

**Comment by zeroleo12345** [comment]
我知道什么回事了，这个api是返回离线下载标签页的内容的，我里面只有4个，旧的删了。
我以为api是返回 “文件->我的接收->离线下载" 的标签页内容而已。
再想请教一下，如果想改到请求这个页面，对应的请求地址和参数，是通过什么工具抓包可以看到的？

**Comment by zeroleo12345** [comment]
试了一下用chrom看报文，发现login的时候和代码中的连接r = self.http.post('http://passport.115.com/?ct=login&ac=ajax&is_ssl=1', passport.form)不一样，而且响应结果和代码的也不一致：
            passport.data = r.content['data']
            self._user_id = r.content['data']['USER_ID']
想请教下http://passport.115.com/?ct=login&ac=ajax&is_ssl=1这个地址是从哪里找到的？

![image](https://cloud.githubusercontent.com/assets/13072815/9004570/b06054c8-37a9-11e5-90c3-086eb8194b01.png)

![image](https://cloud.githubusercontent.com/assets/13072815/9004584/cc1d9f90-37a9-11e5-9efc-976c7ee153e2.png)

**Comment by shichao-an** [comment]
这个 login url 是以前一直被使用的，应该不会有影响。
`API.get_tasks()` 获得的是任务，`API.downloads_directory.list()` 获得是转移后的离线下载文件，还有其他的系统目录请看 http://115wangpan.readthedocs.org/en/latest/tutorial.html#system-directories

**Comment by zeroleo12345** [comment]
oh，我不是说这个有影响的意思。只是想分析与学习一下整个过程是怎么做的。我目前的环境并没有该请求，从所有报文中还找不到相关的数据返回，你那边环境一直有 http://passport.115.com/?ct=login&ac=ajax&is_ssl=1 这个连接的请求的吗?

**Comment by shichao-an** [comment]
我用 chrome 登录里面请求的 login url 是 http://passport.115.com/?ct=login&ac=ajax&relogin=1&is_ssl=1

**Comment by zeroleo12345** [comment]
可能是我的chrome版本问题，登陆时一些请求会被后面的刷走了。换用fiddler就可以看到了
