### ISSUE TITLE
Task类的list()函数问题

### ISSUE THREAD

**Issue by zeroleo12345** [shichao-an/115wangpan#30]
```
def list(self, count=30, order='user_ptime', asc=False, show_dir=True,
         natsort=True):
    return self.directory.list(count, order, asc, show_dir, natsort)
```

提交离线任务后，如果该TASK是单一文件，没有目录的时候报错。好像是这个功能点还没实现吧?

**Comment by shichao-an** [comment]
如果是文件任务，`Task.list()` 会报 "This task is a file task with no associated directory."，因为它调用了 `Task.directory` ([u115/api.py#L1624](https://github.com/shichao-an/115wangpan/blob/master/u115/api.py#L1624))。
